version: '3'
services:
  app:
    build: .
    container_name: Lister
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@prismaClient:5432/Lister
      - JWT_SECRET=ngfcxGFGFCHG6263
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - prismaClient
    volumes:
      - .:/app

  prismaClient:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Lister
    ports:
      - "5440:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: